/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import { useEffect, useMemo, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { ImageList, ImageListItem, ImageListItemBar } from "@mui/material";
import { useResponsive } from "../lib/contexts/ResponsiveContext";

const Gallery: NextPage = () => {
  const [data, setData] = useState<Array<any>>([]);
  const [columns, setColumns] = useState(2);
  const { breakpoint } = useResponsive();

  useEffect(() => {
    const dimension = [300, 500, 700];
    const random = () =>
      dimension[Math.floor(Math.random() * dimension.length)];
    const temp = [...Array(100)].map(() => ({
      width: 400,
      height: random(),
    }));
    setData(temp);
  }, []);

  useEffect(() => {
    setColumns(breakpoint.lg ? 6 : breakpoint.md ? 4 : 2);
  }, [breakpoint]);

  useEffect(() => console.log(columns), [columns]);

  return (
    <>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageList variant="masonry" cols={columns}>
        {data.map((item, index) => (
          <ImageListItem key={index}>
            <Image
              src={`https://picsum.photos/${item.width}/${item.height}?random=${index}&w=248&fit=crop&auto=format`}
              width={item.width}
              height={item.height}
              alt=""
            />
            <ImageListItemBar position="below" title={item.author} />
          </ImageListItem>
        ))}
      </ImageList>
    </>
  );
};

export default Gallery;
