import type { NextPage } from "next";
import Head from "next/head";
import { Box } from "@mui/material";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Box>
  );
};

export default Home;
